version: "3"
services:
  node:
    tty: true
    container_name: node
    build:
      context: ./node
      dockerfile: Dockerfile
    ports:
      - 8089:8089
      - 3000:3000
    volumes:
      - ./www:/var/www
    networks:
      - symfony
      - node_app
    depends_on:
      - symfony
      - database
    environment:
      - WATCHPACK_POLLING=true

  angular:
    build:
      context: ./angular
      dockerfile: Dockerfile
    tty: true
    container_name: angular
    ports:
      - 8100:8100
      - 4200:4200
    volumes:
      - ./www:/usr/src/www
    networks:
      - symfony
    depends_on:
      - symfony
    environment:
      - WATCHPACK_POLLING=true

  firebase:
    build:
      context: ./firebase
      dockerfile: Dockerfile
    tty: true
    container_name: firebase
    ports:
      - 3033:3033
    volumes:
      - ./www:/www
    environment:
      - WATCHPACK_POLLING=true

  database:
    container_name: database
    image: mysql:5.7
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: Foutaise.1
      MYSQL_USER: doloresHaze
      MYSQL_PASSWORD: Foutaise.1
    volumes:
      - ./database-conf.cnf:/etc/mysql/conf.d/database-conf.cnf
    networks:
      - symfony_app
  symfony:
    container_name: symfony
    ports:
      - 8000:8000
      - 80:80
    build:
      context: ./symfony
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
    depends_on:
      - database
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - symfony_app

volumes:
  symfony_app_var:
  symfony_app_vendor:
  db_app:
  app:
networks:
  symfony_app:
  symfony:
  node_app:
