# Utilisation de l'image officielle CommandBox
FROM ortussolutions/commandbox

# Répertoire de travail dans le conteneur
WORKDIR /app

# Copie des fichiers de l'application dans le conteneur
COPY . /app

# Exposer le port sur lequel votre application ColdFusion fonctionne
EXPOSE 8080

# Commande pour démarrer l'application
# CMD ["start", "--rewritesEnable", "true"]